const data = [{
	"title":"设置",
	"name":"settings",
	"icon":"el-icon-setting",
	"children":[{
		"title":"系统相关",
		"name":"system-settings",
		"icon":"el-icon-s-operation",
		"children":[{
			"title":"功能管理",
			"name":"menu-manage",
			"icon":"el-icon-s-order",
			"path":"/menu-manage"
		},{
			"title":"指令管理",
			"name":"instructs-manage",
			"icon":"el-icon-s-flag",
			"path":"/instructs-manage"
		}]
	},{
		"title":"用户相关",
		"name":"user-settings",
		"icon":"el-icon-user",
		"children":[{
			"title":"用户角色",
			"icon":"el-icon-setting",
			"name":"user-role",
			"path":"/user-role"
		},{
			"title":"用户列表",
			"icon":"el-icon-s-management",
			"name":"user-list",
			"path":"/user-list"
		}]
	}]
},{
	"title":"报表",
	"name":"reports",
	"icon":"el-icon-s-marketing",
	"children":[{
		"title":"echarts",
		"name":"echarts",
		"icon":"el-icon-s-data",
		"path":"/echarts",
		"children":[]
	}]
}]

export default data